# Generated by Django 4.1.7 on 2023-03-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
